import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import Header from '@/components/layout/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import Footer from '@/components/layout/Footer';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '900'] });

export const metadata: Metadata = {
    title: 'VikinX',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${poppins.className}`}>
                <ClerkProvider appearance={{ baseTheme: dark }}>
                        <Header />
                        <main className='container mx-auto px-4 md:px-6 lg:px-8 '>
                            {children}
                        </main>
                        <Footer />
                </ClerkProvider>
            </body>
        </html>
    );
}
